#!/usr/bin/env bash

sudo apt-get update

# upgrading causes a problem for Grub and debconf bugs you about it
# DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade

# install the bare minimum to survive
sudo apt-get -y install screen git curl

# install MongoDB
sudo apt-get -y install mongodb

# change the MongoDB listen port
sudo sed -i 's/#port = 27017/port = 27017/' /etc/mongodb.conf

# initialize MongoDB with some default data
# FIXME

# install the JVM - unluckily there's no openjdk-7-jdk-headless
sudo apt-get -y install openjdk-7-jdk

# oh noes, install Maven
sudo apt-get -y install maven

# have brain-dead Maven understand which Java to use
cat << EOF >> /home/vagrant/.profile
export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64/jre
EOF

source /home/vagrant/.profile

# install node
cd /tmp
curl https://raw.github.com/creationix/nvm/master/install.sh | sh
source /home/vagrant/.nvm/nvm.sh

nvm install 0.10.21
nvm use 0.10.21
nvm alias default 0.10.21

# install Bower
npm install -g bower

# install phantow
npm install -g phantomjs

# install Grunt
npm install -g grunt-cli

# init project
cd /vagrant
npm install
bower install

